baseURL: "https://phidra.github.io/blog/"
languageCode: "fr-fr"
title: "Phidra's blog"
theme: "m10c"

params:
    author: "phidra"
    description: "blog tech C++ python dev"
    avatar: "/img/general/phi_medium_fond_blanc.png"
